/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package club_view;

import club_controller.AuthenticationController;
import club_controller.NavigationController;
import club_model.AuthenticationModel;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author A$iri
 */
public class FrmRegister3 extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmRegister3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtLname = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnRegister2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnBackLogin = new javax.swing.JButton();
        btnClear2 = new javax.swing.JButton();
        txtMobile = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtRole = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLname.setBackground(new java.awt.Color(204, 204, 204));
        txtLname.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtLname.setForeground(new java.awt.Color(56, 56, 56));
        txtLname.setText(" Lname");
        txtLname.setBorder(null);
        txtLname.setName("txtLname"); // NOI18N
        txtLname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLnameFocusLost(evt);
            }
        });
        txtLname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLnameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtLnameMouseExited(evt);
            }
        });
        jPanel3.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 140, 30));

        txtPassword.setBackground(new java.awt.Color(204, 204, 204));
        txtPassword.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(56, 56, 56));
        txtPassword.setText("Password");
        txtPassword.setBorder(null);
        txtPassword.setName("txtPassword"); // NOI18N
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 300, 30));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("I have an Account");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 160, 30));

        btnRegister2.setBackground(new java.awt.Color(255, 255, 255));
        btnRegister2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister2.setForeground(new java.awt.Color(30, 30, 30));
        btnRegister2.setText("Register");
        btnRegister2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegister2.setContentAreaFilled(false);
        btnRegister2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister2.setName("btnRegister"); // NOI18N
        btnRegister2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegister2MouseEntered(evt);
            }
        });
        btnRegister2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegister2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 70, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel4.setText("Ready to Register");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, 40));

        btnBackLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnBackLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBackLogin.setForeground(new java.awt.Color(30, 30, 30));
        btnBackLogin.setText("Back to Log in");
        btnBackLogin.setToolTipText("");
        btnBackLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBackLogin.setContentAreaFilled(false);
        btnBackLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackLogin.setName("btnBackLogin"); // NOI18N
        btnBackLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnBackLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 160, 30));

        btnClear2.setBackground(new java.awt.Color(255, 255, 255));
        btnClear2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear2.setForeground(new java.awt.Color(30, 30, 30));
        btnClear2.setText("Clear");
        btnClear2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClear2.setContentAreaFilled(false);
        btnClear2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear2.setName("btnClear"); // NOI18N
        btnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnClear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 80, 30));

        txtMobile.setBackground(new java.awt.Color(204, 204, 204));
        txtMobile.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtMobile.setForeground(new java.awt.Color(56, 56, 56));
        txtMobile.setText(" Mobile");
        txtMobile.setBorder(null);
        txtMobile.setName("txtMobile"); // NOI18N
        txtMobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMobileFocusLost(evt);
            }
        });
        txtMobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMobileMouseClicked(evt);
            }
        });
        jPanel3.add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 300, 30));

        txtFname.setBackground(new java.awt.Color(204, 204, 204));
        txtFname.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtFname.setForeground(new java.awt.Color(56, 56, 56));
        txtFname.setText(" Fname");
        txtFname.setBorder(null);
        txtFname.setName("txtFname"); // NOI18N
        txtFname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnameFocusLost(evt);
            }
        });
        txtFname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFnameMouseClicked(evt);
            }
        });
        jPanel3.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 30));

        txtAge.setBackground(new java.awt.Color(204, 204, 204));
        txtAge.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtAge.setForeground(new java.awt.Color(56, 56, 56));
        txtAge.setText(" Age");
        txtAge.setBorder(null);
        txtAge.setName("txtAge"); // NOI18N
        txtAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAgeFocusLost(evt);
            }
        });
        txtAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAgeMouseClicked(evt);
            }
        });
        jPanel3.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 300, 30));

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(56, 56, 56));
        txtEmail.setText(" Email");
        txtEmail.setBorder(null);
        txtEmail.setName("txtEmail"); // NOI18N
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 300, 30));

        txtRole.setBackground(new java.awt.Color(204, 204, 204));
        txtRole.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtRole.setForeground(new java.awt.Color(56, 56, 56));
        txtRole.setText("Role");
        txtRole.setBorder(null);
        txtRole.setName("txtMobile"); // NOI18N
        txtRole.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRoleFocusLost(evt);
            }
        });
        txtRole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRoleMouseClicked(evt);
            }
        });
        jPanel3.add(txtRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 300, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnRegister2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegister2MouseEntered
        btnRegister2.setBackground(Color.RED);
    }//GEN-LAST:event_btnRegister2MouseEntered

    private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear2ActionPerformed
        txtFname.setText("");
        txtLname.setText("");
        txtAge.setText("");
        txtMobile.setText("");
        txtEmail.setText("");
        txtPassword.setText("");
        txtRole.setText("");
    }//GEN-LAST:event_btnClear2ActionPerformed

    private void txtFnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnameFocusGained
        
    }//GEN-LAST:event_txtFnameFocusGained

    private void txtFnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFnameMouseClicked
        txtFname.setText("");
    }//GEN-LAST:event_txtFnameMouseClicked

    private void txtLnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLnameMouseExited
        
    }//GEN-LAST:event_txtLnameMouseExited

    private void txtFnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnameFocusLost
        
    }//GEN-LAST:event_txtFnameFocusLost

    private void txtLnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLnameMouseClicked
        txtLname.setText("");
    }//GEN-LAST:event_txtLnameMouseClicked

    private void txtLnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLnameFocusLost
        
    }//GEN-LAST:event_txtLnameFocusLost

    private void txtAgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgeMouseClicked
        txtAge.setText("");
    }//GEN-LAST:event_txtAgeMouseClicked

    private void txtAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAgeFocusLost
       
    }//GEN-LAST:event_txtAgeFocusLost

    private void txtMobileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMobileMouseClicked
        txtMobile.setText("");
    }//GEN-LAST:event_txtMobileMouseClicked

    private void txtMobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMobileFocusLost
       
    }//GEN-LAST:event_txtMobileFocusLost

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
       txtEmail.setText("");
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
       
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
         
    }//GEN-LAST:event_txtPasswordFocusLost

    private void btnBackLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackLoginActionPerformed
         NavigationController navigation = new  NavigationController(this);
         navigation.navigateToLogin(new FrmLogin());
    }//GEN-LAST:event_btnBackLoginActionPerformed

    private void btnRegister2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister2ActionPerformed
         AuthenticationModel registerModel = new AuthenticationModel();
         registerModel.setFname(txtFname.getText());
         registerModel.setLname(txtLname.getText());
         registerModel.setAge(Integer.parseInt(txtAge.getText()));
         registerModel.setEmail(txtEmail.getText());
         registerModel.setPassword(txtPassword.getText());
         registerModel.setStaff_role(txtRole.getText());
         
         AuthenticationController registerType = new AuthenticationController ();                          
                  try {                          
                         registerType .registerStaffMember (registerModel);
                  } catch (SQLException ex) {
                          Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
                  }

    }//GEN-LAST:event_btnRegister2ActionPerformed

    private void txtRoleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRoleFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoleFocusLost

    private void txtRoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRoleMouseClicked
        txtRole.setText("");
    }//GEN-LAST:event_txtRoleMouseClicked


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegister3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegister3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegister3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegister3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegister3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackLogin;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnRegister2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtRole;
    // End of variables declaration//GEN-END:variables
}
